import os
import re

NOTES_BASE = "/home/saransh/MBA_Notes"

def save_unit_file(subject_folder: str, unit_num: int, unit_title: str, subject_code: str, subject_title: str, content_markdown: str):
    folder_path = os.path.join(NOTES_BASE, subject_folder)
    os.makedirs(folder_path, exist_ok=True)
    clean_title = re.sub(r'[^a-zA-Z0-9_]', '_', unit_title).strip('_')
    filename = f"Unit_{unit_num:02d}_{clean_title[:35]}.md"
    file_path = os.path.join(folder_path, filename)
    
    full_doc = f"""# 🎓 {subject_title} ({subject_code})
# 📖 UNIT {unit_num:02d}: {unit_title.upper()}
> **Official NMIMS Distance MBA Curriculum Master Note** • Comprehensive Gold-Standard Courseware.

---

{content_markdown.strip()}

---
*Generated by SM Command Center RAG Master Notes Engine • Grounded in Official NMIMS Distance Education Courseware.*
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(full_doc)

print("Helper defined.")
