import os
import re

NOTES_BASE = "/home/saransh/MBA_Notes"

def save_note(folder, num, title, code, sub_title, body):
    folder_path = os.path.join(NOTES_BASE, folder)
    os.makedirs(folder_path, exist_ok=True)
    clean_title = re.sub(r'[^a-zA-Z0-9_]', '_', title).strip('_')
    filename = f"Unit_{num:02d}_{clean_title[:35]}.md"
    file_path = os.path.join(folder_path, filename)

    doc = f"""# 🎓 {sub_title} ({code})
# 📖 UNIT {num:02d}: {title.upper()}
> **Official NMIMS Distance MBA Curriculum Master Note** • Comprehensive Gold-Standard Courseware.

---

{body.strip()}

---
*Generated by SM Command Center RAG Master Notes Engine • Grounded in Official NMIMS Distance Education Courseware.*
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(doc)

def gen_fa():
    sub = "Financial Accounting"
    code = "RETFINACC1"
    folder = "Financial_Accounting"

    units = [
        (1, "Introduction to Financial Accounting", """
1. The Core Purpose & Evolution of Financial Accounting
- Strategic Role: Financial accounting systematically records, classifies, summarizes, and communicates financial transactions of an enterprise to external stakeholders (investors, banks, tax authorities).
- Statutory Framework: Governed by the Companies Act 2013, Indian Accounting Standards (Ind-AS converged with IFRS), and ICAI pronouncements.
- Key Accounting Conventions: Entity Concept, Money Measurement, Going Concern, Periodicity, Accrual Principle, Conservatism (Prudence), and the Matching Concept.

+---------------------------------------------------------------------------------+
|                       FINANCIAL ACCOUNTING ECOSYSTEM                            |
+---------------------------------------------------------------------------------+
|  [ Source Documents ] --> Invoices, receipts, vouchers, bank statements          |
|  [ Journal Ledger ]   --> Chronological entry (Kafka stream) & T-Accounts       |
|  [ Trial Balance ]    --> Arithmetic integrity checksum assertion               |
|  [ Financial Reports ]--> Balance Sheet, P&L Statement, Cash Flow Statement     |
+---------------------------------------------------------------------------------+

2. Capital Expenditure (CapEx) vs Revenue Expenditure (OpEx)
| Dimension | Capital Expenditure (CapEx) | Revenue Expenditure (OpEx) |
| :--- | :--- | :--- |
| **Purpose** | Acquisition or expansion of long-term economic assets | Sustaining day-to-day operational capability |
| **Benefit Horizon** | Multiple future fiscal years | Consumed entirely within current fiscal period |
| **Accounting Treatment** | Capitalized on Balance Sheet (Non-Current Asset) | Expensed directly in Profit & Loss Statement |
| **Corporate Example** | Buying GPU AI Server Clusters (₹5,000,000) | Monthly Cloud API Hosting Fees (₹80,000) |

3. Mathematical Derivations & Formulas
```latex
\\text{Net Income} = \\text{Total Revenues} - \\text{Total Expenses}
```
```latex
\\text{Ending Capital} = \\text{Opening Capital} + \\text{Net Profit} - \\text{Drawings}
```

4. Practical Case Applications
- **Tata Steel (ERP Accounting Integration):**
  - *Challenge:* Multi-currency operations across 26 countries created severe reporting delays and balance sheet reconciliation errors.
  - *Strategy:* Implemented SAP ERP enterprise ledger architecture to automate transactional journaling and standardize Ind-AS reporting.
  - *Outcome:* Reduced closing cycle time by 40% and eliminated consolidated balance sheet discrepancies.
"""),
        (2, "Accounting Process & Double-Entry Rules", """
1. The Universal Double-Entry System
- Luca Pacioli Axiom (1494): Every economic transaction has a dual aspect. For every debit, there is an equal and opposite credit.
- The Accounting Equation: Assets = Liabilities + Owner's Equity ($A = L + E$).

+---------------------------------------------------------------------------------+
|                        THE 3 GOLDEN RULES OF ACCOUNTING                         |
+---------------------------------------------------------------------------------+
|  1. Personal Accounts (Entities/Vendors) --> Debit the Receiver, Credit Giver    |
|  2. Real Accounts (Assets/Property)       --> Debit What Comes In, Credit Out    |
|  3. Nominal Accounts (Expenses/Income)   --> Debit All Expenses, Credit Incomes  |
+---------------------------------------------------------------------------------+

2. Expanded Accounting Equation Mechanics
```latex
\\text{Assets} = \\text{Liabilities} + \\text{Owner's Equity}
```
```latex
\\text{Assets} + \\text{Expenses} + \\text{Drawings} = \\text{Liabilities} + \\text{Capital} + \\text{Revenues}
```

3. Practical Case Applications
- **Infosys (Two-Phase Commit Ledger Validation):**
  - *Challenge:* Handling 500,000+ monthly client billing transactions across global accounts.
  - *Strategy:* Enforced automated two-phase commit ledger validation asserting $A = L + E$ before committing to the main Oracle database.
  - *Outcome:* Zero reconciliation failures during statutory audit.
"""),
        (3, "Financial Statements & Core Fundamental Equations", """
1. The 3 Primary Financial Statements
- Balance Sheet: Static solvency snapshot at a discrete point in time ($A = L + E$).
- Profit & Loss Statement (Income Statement): Operational profitability over a duration.
- Cash Flow Statement: Segregates Operating (CFO), Investing (CFI), and Financing (CFF) cash flows.

+---------------------------------------------------------------------------------+
|                        FINANCIAL STATEMENT ARCHITECTURE                         |
+---------------------------------------------------------------------------------+
|  [ Balance Sheet ]   --> Solvency Snapshot (Assets = Liabilities + Equity)      |
|  [ Income Statement ]--> Operating Performance (Net Income = Revenue - OpEx)    |
|  [ Cash Flow ]       --> Liquidity Flow (Delta Cash = CFO + CFI + CFF)          |
+---------------------------------------------------------------------------------+

2. Key Formulas & Ratios
```latex
\\text{Operating Profit (EBIT)} = \\text{Gross Profit} - \\text{Selling \\& Admin Expenses} - \\text{Depreciation}
```
```latex
\\text{Working Capital} = \\text{Current Assets} - \\text{Current Liabilities}
```

3. Practical Case Applications
- **Apple Inc (Managing Negative Working Capital):**
  - *Challenge:* Optimizing cash velocity without incurring short-term debt.
  - *Strategy:* Negotiated 90-day supplier payment terms while collecting cash instantly from customers.
  - *Outcome:* Generated billions in non-debt working capital float.
"""),
        (4, "Preparation of Financial Statements & Schedule III Format", """
1. Statutory Preparation under Companies Act 2013
- Schedule III Division II: Mandates vertical presentation of Balance Sheets and P&L for Ind-AS compliant companies.
- Depreciation Methods: Straight-Line Method (SLM) for uniform usage vs Written Down Value (WDV) for accelerating tax shields.

+---------------------------------------------------------------------------------+
|                       SCHEDULE III BALANCE SHEET FORMAT                         |
+---------------------------------------------------------------------------------+
|  I. EQUITY AND LIABILITIES                                                      |
|     1. Shareholders' Funds (Share Capital, Reserves & Surplus)                  |
|     2. Non-Current Liabilities (Long-Term Borrowings, Deferred Tax)             |
|     3. Current Liabilities (Trade Payables, Short-Term Provisions)              |
|  II. ASSETS                                                                     |
|     1. Non-Current Assets (Property, Plant, Equipment, Intangibles)             |
|     2. Current Assets (Inventories, Trade Receivables, Cash & Equivalents)      |
+---------------------------------------------------------------------------------+

2. Depreciation Formulas
```latex
\\text{SLM Depreciation} = \\frac{\\text{Historical Cost} - \\text{Scrap Value}}{\\text{Useful Life in Years}}
```

3. Practical Case Applications
- **Larsen & Toubro (L&T Infrastructure Depreciation):**
  - *Challenge:* Depreciating heavy construction equipment under varying operational usage.
  - *Strategy:* Adopted WDV method for tax optimization while maintaining SLM for reporting asset life.
  - *Outcome:* Maximized operational tax cash flows while ensuring Schedule III compliance.
"""),
        (5, "Financial Reporting Standards I (GAAP & Ind-AS)", """
1. The Ind-AS / IFRS Convergence Paradigm
- Core Objective: Harmonize Indian corporate reporting with International Financial Reporting Standards (IFRS).
- Ind-AS 115 (Revenue Recognition): Replaces legacy rule-based recognition with a 5-step principle-based framework.

+---------------------------------------------------------------------------------+
|                   IND-AS 115 5-STEP REVENUE RECOGNITION MODEL                   |
+---------------------------------------------------------------------------------+
|  Step 1: Identify the Contract with Customer                                    |
|  Step 2: Identify Separate Performance Obligations in the Contract              |
|  Step 3: Determine the Total Transaction Price                                  |
|  Step 4: Allocate Transaction Price to Separate Performance Obligations         |
|  Step 5: Recognize Revenue as / when each Performance Obligation is Satisfied   |
+---------------------------------------------------------------------------------+

2. Practical Case Applications
- **Wipro (Software + Maintenance Bundled Contracts):**
  - *Challenge:* Unbundling ₹100M multi-year enterprise contracts comprising software licenses, hardware, and support.
  - *Strategy:* Applied Ind-AS 115 standalone selling price allocation to recognize software upon delivery and amortize support over 36 months.
  - *Outcome:* Eliminated revenue restatement risks during SEC and SEBI filings.
"""),
        (6, "Financial Reporting Standards II (Leases & PPE)", """
1. Ind-AS 116 (Leases) & Ind-AS 16 (PPE)
- Elimination of Off-Balance-Sheet Leases: Operating leases must be capitalized as a **Right-of-Use (ROU) Asset** with a matching **Lease Liability**.
- Ind-AS 16 (PPE): Requires component accounting and periodic impairment testing under Ind-AS 36.

+---------------------------------------------------------------------------------+
|                        IND-AS 116 LEASE BALANCE SHEET SHIFT                     |
+---------------------------------------------------------------------------------+
|  Legacy Treatment --> Rent expensed in P&L; 0 Asset/Liability on Balance Sheet |
|  Ind-AS 116       --> ROU Asset (Dr) + Lease Liability (Cr) recorded on Day 1   |
|  Income Statement --> Rent replaced by ROU Depreciation + Lease Interest Expense|
+---------------------------------------------------------------------------------+

2. Practical Case Applications
- **IndiGo Airlines (Aircraft Fleet Lease Capitalization):**
  - *Challenge:* Transitioning 250+ leased aircraft from operating leases to balance sheet assets.
  - *Strategy:* Capitalized ₹30,000+ Crores of ROU assets, raising reported EBITDA while providing debt transparency.
  - *Outcome:* Provided international debt rating agencies with complete transparency into fleet commitments.
"""),
        (7, "Corporate Financial Statements & Share Capital", """
1. Corporate Capital Architecture
- Share Capital Taxonomy: Authorized Capital, Issued Capital, Subscribed Capital, Paid-up Capital.
- Securities Premium Account (Section 52): Used exclusively for bonus shares, writing off preliminary expenses, or buybacks.
- Buyback of Shares (Section 68): Repurchasing company shares from open market to reduce equity base and increase EPS.

+---------------------------------------------------------------------------------+
|                        CORPORATE EQUITY COMPOSITION                             |
+---------------------------------------------------------------------------------+
|  [ Share Capital ]      --> Equity Shares (Voting) + Preference Shares (Fixed)   |
|  [ Reserves & Surplus ] --> Securities Premium, Retained Earnings, General Res. |
|  [ Capital Servicing ]  --> Dividend Payouts vs Share Buybacks (EPS Accretion)  |
+---------------------------------------------------------------------------------+

2. Key Formula
```latex
\\text{Basic EPS} = \\frac{\\text{Net Profit After Tax} - \\text{Preference Share Dividends}}{\\text{Weighted Average Number of Equity Shares Outstanding}}
```

3. Practical Case Applications
- **HDFC Bank (Capital Adequacy & Share Premium Reserves):**
  - *Challenge:* Maintaining RBI mandated Capital Adequacy Ratio (CAR) during rapid loan book expansion.
  - *Strategy:* Issued equity shares at premium, channeling ₹10,000+ Crores into Securities Premium Account to bolster core Tier-1 equity.
  - *Outcome:* Achieved CAR of 18.8%, securing banking stability.
"""),
        (8, "Statement of Cash Flows (AS-3 / Ind-AS 7)", """
1. Cash Flow Mechanics (Indirect Method)
- Principle: Net Profit is converted into operating cash by adding back non-cash expenses and adjusting for working capital changes.
- Three Segments: Operating Activities (CFO), Investing Activities (CFI), Financing Activities (CFF).

+---------------------------------------------------------------------------------+
|                     INDIRECT CASH FLOW STATEMENT PIPELINE                       |
+---------------------------------------------------------------------------------+
|  Net Profit Before Tax                                                          |
|  + Non-Cash Adjustments (Depreciation, Amortization, Loss on Sale of Assets)   |
|  - Non-Operating Incomes (Interest/Dividend Received, Profit on Sale)          |
|  = Operating Profit Before Working Capital Changes                              |
|  - Increase in Current Assets (Inventory, Receivables)                          |
|  + Increase in Current Liabilities (Trade Payables, Provisions)                 |
|  - Income Taxes Paid                                                            |
|  = CASH FLOW FROM OPERATING ACTIVITIES (CFO)                                    |
+---------------------------------------------------------------------------------+

2. Free Cash Flow Formula
```latex
\\Delta \\text{Cash} = \\text{CFO} + \\text{CFI} + \\text{CFF}
```

3. Practical Case Applications
- **Amazon (Free Cash Flow Focus):**
  - *Challenge:* Operating at low accounting net margins while funding continuous global expansion.
  - *Strategy:* Maintained immense positive CFO through high inventory turnover and customer cash receipts.
  - *Outcome:* Funded multi-billion dollar datacenter builds without relying on debt dilution.
"""),
        (9, "Analysis of Financial Statements I (Liquidity & Solvency)", """
1. Ratio Analysis: Liquidity & Solvency
- Liquidity Ratios: Current Ratio (2.0:1 benchmark), Quick Ratio (1.0:1 benchmark), Cash Ratio.
- Solvency Ratios: Debt-to-Equity, Interest Coverage Ratio (EBIT / Interest).

+---------------------------------------------------------------------------------+
|                       LIQUIDITY & SOLVENCY BENCHMARKS                           |
+---------------------------------------------------------------------------------+
|  Current Ratio (CA / CL)          --> Benchmark: 2.0 : 1                        |
|  Quick Ratio ((CA - Stock) / CL)  --> Benchmark: 1.0 : 1                        |
|  Debt-to-Equity (Total Debt / NW) --> Benchmark: <= 2.0 : 1                     |
|  Interest Coverage (EBIT / Int)   --> Benchmark: >= 3.0x                        |
+---------------------------------------------------------------------------------+

2. Key Formulas
```latex
\\text{Current Ratio} = \\frac{\\text{Current Assets}}{\\text{Current Liabilities}}
```
```latex
\\text{Interest Coverage Ratio} = \\frac{\\text{EBIT}}{\\text{Interest Expense}}
```

3. Practical Case Applications
- **Tata Motors (De-leveraging Debt-to-Equity):**
  - *Challenge:* Heavy debt burden following Jaguar Land Rover acquisition.
  - *Strategy:* Applied strict cash flow discipline and equity monetization to raise Interest Coverage Ratio above 4.5x.
  - *Outcome:* Upgraded credit rating to positive outlook.
"""),
        (10, "Analysis of Financial Statements II (DuPont & Profitability)", """
1. DuPont Analysis & Profitability Decomposition
- DuPont 3-Step Identity: $\\text{ROE} = \\text{Profit Margin} \\times \\text{Asset Turnover} \\times \\text{Equity Multiplier}$.
- Cash Conversion Cycle (CCC): Measures the days elapsed from paying for inventory to collecting customer cash ($\text{DIO} + \text{DSO} - \text{DPO}$).

+---------------------------------------------------------------------------------+
|                         DUPONT 3-STEP ROE DECOMPOSITION                         |
+---------------------------------------------------------------------------------+
|  ROE = [ Net Profit Margin ] x [ Asset Turnover ] x [ Equity Multiplier ]       |
|  ROE = ( Net Income / Sales ) x ( Sales / Total Assets ) x ( Assets / Equity )  |
+---------------------------------------------------------------------------------+

2. Key Formulas
```latex
\\text{ROE} = \\left( \\frac{\\text{Net Income}}{\\text{Sales}} \\right) \\times \\left( \\frac{\\text{Sales}}{\\text{Total Assets}} \\right) \\times \\left( \\frac{\\text{Total Assets}}{\\text{Shareholders' Equity}} \\right)
```

3. Practical Case Applications
- **ITC Limited (High ROE through Margin & Asset Velocity):**
  - *Challenge:* Generating industry-leading ROE without debt leverage.
  - *Strategy:* Maintained 28%+ Net Profit Margin and debt-free balance sheet, driving ROE exceeding 30% entirely through operational efficiency.
  - *Outcome:* Top-quartile FMCG shareholder value creation.
"""),
        (11, "Ethics in Accounting & Corporate Governance", """
1. Ethics, Internal Controls & Fraud Detection
- The Fraud Triangle: Opportunity (weak internal controls), Pressure (market earnings expectations), and Rationalization.
- Whistleblower Protection & Audit Committees: Mandatory under Section 177 of Companies Act 2013 and SEBI LODR.

+---------------------------------------------------------------------------------+
|                             THE FRAUD TRIANGLE MODEL                            |
+---------------------------------------------------------------------------------+
|                         [ PRESSURE / INCENTIVE ]                                |
|                                /        \\                                       |
|                  [ OPPORTUNITY ] <--------> [ RATIONALIZATION ]                 |
+---------------------------------------------------------------------------------+

2. Key Formula
```latex
\\text{M-Score} = -4.84 + 0.920 \\cdot \\text{DSRI} + 0.528 \\cdot \\text{GMI} + 0.404 \\cdot \\text{AQI} + \\dots
```

3. Practical Case Applications
- **Satyam Computer Services (2009 Corporate Governance Scandal):**
  - *Challenge:* Chairman confessed to fabricating ₹5,040 Crores of non-existent fixed deposits over years.
  - *Strategy:* Government intervention, board replacement, and forensic audit leading to takeover by Tech Mahindra.
  - *Outcome:* Overhaul of Indian corporate governance laws, introducing mandatory audit partner rotation.
"""),
        (12, "Emerging Trends in Accounting (Forensic & ESG)", """
1. Emerging Accounting Paradigms
- Forensic Accounting: Specialized investigative auditing combining data analytics and Benford's Law to uncover financial fraud.
- ESG & BRSR Reporting: Business Responsibility and Sustainability Reporting mandated by SEBI for top 1,000 listed entities.
- Carbon Accounting: Recording carbon emission liabilities and carbon offset credit assets on balance sheets.

+---------------------------------------------------------------------------------+
|                     EMERGING ACCOUNTING DIMENSIONS ECOSYSTEM                    |
+---------------------------------------------------------------------------------+
|  [ Forensic Accounting ] --> Data pattern analysis, Benford's Law audits        |
|  [ ESG & BRSR ]          --> Scope 1, 2, 3 carbon emissions & social metrics     |
|  [ AI & Cloud Ledgers ]  --> Automated smart reconciliation, blockchain trails  |
+---------------------------------------------------------------------------------+

2. Benford's Law Formulation
```latex
P(d) = \\log_{10}\\left(1 + \\frac{1}{d}\\right) \\quad \\text{for } d \\in \\{1, 2, \\dots, 9\\}
```

3. Practical Case Applications
- **SEBI Top 1,000 Listed Companies (BRSR Compliance):**
  - *Challenge:* Quantifying Scope 1 (direct fuel), Scope 2 (electricity), and Scope 3 (supply chain) greenhouse gas emissions.
  - *Strategy:* Integrated ESG data capture into corporate ERPs to produce audited BRSR disclosures.
  - *Outcome:* Attracted global ESG sustainability mutual fund investments into Indian equities.
""")
    ]

    for num, title, body in units:
        save_note(folder, num, title, code, sub, body)
    print("Financial Accounting complete.")

if __name__ == "__main__":
    gen_fa()
