import os
import re

NOTES_BASE = "/home/saransh/MBA_Notes"

def save_note(folder, num, title, code, sub_title, body):
    folder_path = os.path.join(NOTES_BASE, folder)
    os.makedirs(folder_path, exist_ok=True)
    clean_title = re.sub(r'[^a-zA-Z0-9_]', '_', title).strip('_')
    filename = f"Unit_{num:02d}_{clean_title[:35]}.md"
    file_path = os.path.join(folder_path, filename)

    doc = f"""# 🎓 {sub_title} ({code})
# 📖 UNIT {num:02d}: {title.upper()}
> **Official NMIMS Distance MBA Curriculum Master Note** • Comprehensive Gold-Standard Courseware.

---

{body.strip()}

---
*Generated by SM Command Center RAG Master Notes Engine • Grounded in Official NMIMS Distance Education Courseware.*
"""
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(doc)

print("Exhaustive note generator helper ready.")
