"""phase1_universal_command_center_infrastructure

Revision ID: cd63c388da75
Revises: 
Create Date: 2026-08-12 21:21:35.243292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd63c388da75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_app_state_key'), 'app_state', ['key'], unique=False)
    op.create_table('course_progress_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=128), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('sections_completed', sa.Integer(), nullable=False),
    sa.Column('minutes_spent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_progress_logs_course_id'), 'course_progress_logs', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_progress_logs_id'), 'course_progress_logs', ['id'], unique=False)
    op.create_table('daily_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('applications_sent', sa.Integer(), nullable=False),
    sa.Column('deep_coding_solved', sa.Integer(), nullable=False),
    sa.Column('deep_dev_blocks', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_inputs_date'), 'daily_inputs', ['date'], unique=True)
    op.create_index(op.f('ix_daily_inputs_id'), 'daily_inputs', ['id'], unique=False)
    op.create_table('drill_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drill_logs_category'), 'drill_logs', ['category'], unique=False)
    op.create_index(op.f('ix_drill_logs_id'), 'drill_logs', ['id'], unique=False)
    op.create_table('mba_session_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('ai_notes_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mba_session_logs_id'), 'mba_session_logs', ['id'], unique=False)
    op.create_index(op.f('ix_mba_session_logs_subject'), 'mba_session_logs', ['subject'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('freed_ram_mb', sa.Float(), nullable=False),
    sa.Column('terminated_pids', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_action'), 'system_logs', ['action'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('persona_type', sa.String(length=64), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_persona_type'), 'workspaces', ['persona_type'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('daily_trackers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'date', name='uq_tracker_workspace_date')
    )
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_status'), 'entities', ['status'], unique=False)
    op.create_index(op.f('ix_entities_workspace_id'), 'entities', ['workspace_id'], unique=False)
    op.create_index('ix_entities_workspace_status', 'entities', ['workspace_id', 'status'], unique=False)
    op.create_index('ix_entities_workspace_type', 'entities', ['workspace_id', 'entity_type'], unique=False)
    op.create_table('ingestion_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_logs_workspace_id'), 'ingestion_logs', ['workspace_id'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=True),
    sa.Column('default_target', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_metric_workspace_key')
    )
    op.create_index(op.f('ix_metric_definitions_workspace_id'), 'metric_definitions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_definitions_workspace_id'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index(op.f('ix_ingestion_logs_workspace_id'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_index('ix_entities_workspace_type', table_name='entities')
    op.drop_index('ix_entities_workspace_status', table_name='entities')
    op.drop_index(op.f('ix_entities_workspace_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_status'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('daily_trackers')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_persona_type'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_action'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_mba_session_logs_subject'), table_name='mba_session_logs')
    op.drop_index(op.f('ix_mba_session_logs_id'), table_name='mba_session_logs')
    op.drop_table('mba_session_logs')
    op.drop_index(op.f('ix_drill_logs_id'), table_name='drill_logs')
    op.drop_index(op.f('ix_drill_logs_category'), table_name='drill_logs')
    op.drop_table('drill_logs')
    op.drop_index(op.f('ix_daily_inputs_id'), table_name='daily_inputs')
    op.drop_index(op.f('ix_daily_inputs_date'), table_name='daily_inputs')
    op.drop_table('daily_inputs')
    op.drop_index(op.f('ix_course_progress_logs_id'), table_name='course_progress_logs')
    op.drop_index(op.f('ix_course_progress_logs_course_id'), table_name='course_progress_logs')
    op.drop_table('course_progress_logs')
    op.drop_index(op.f('ix_app_state_key'), table_name='app_state')
    op.drop_table('app_state')
    # ### end Alembic commands ###
